# Generated by Django 5.2.6 on 2026-08-17 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('register', 'User Registered'), ('email_verified', 'Email Verified'), ('login_success', 'Login Successful'), ('login_failed', 'Login Failed'), ('login_otp_sent', 'Login OTP Sent'), ('login_otp_verified', 'Login OTP Verified'), ('login_otp_failed', 'Login OTP Failed'), ('mfa_verified', 'MFA Verified'), ('mfa_setup', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('logout', 'User Logged Out'), ('account_locked', 'Account Locked'), ('password_changed', 'Password Changed'), ('role_requested', 'Role Requested'), ('role_approved', 'Role Approved'), ('role_rejected', 'Role Rejected'), ('user_approved', 'User Approved'), ('media_uploaded', 'Media Uploaded'), ('media_updated', 'Media Updated'), ('media_deleted', 'Media Deleted'), ('media_published', 'Media Published'), ('media_viewed', 'Media Viewed'), ('media_downloaded', 'Media Downloaded'), ('permission_denied', 'Permission Denied'), ('rate_limited', 'Rate Limited'), ('suspicious_activity', 'Suspicious Activity')], max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['action', '-created_at'], name='audit_audit_action_0c6a84_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx')],
            },
        ),
    ]
