# Generated by Django 5.2.6 on 2026-08-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_format',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
