# Generated by Django 5.2.6 on 2026-08-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_mediaasset_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_version',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
