# Generated by Django 5.2.6 on 2026-08-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_mediaasset_file_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaasset',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
